title: Algorithmic Personalization Project
logo: assets/img/logo.png
description: The Algorithmic Personalization Project studies the long-term consequences of recommendation.
show_downloads: true
theme: jekyll-theme-minimal